src/main/java/com/project/roomescape/controller/QuizController.java

QuizController의 Quiz 조회하기와 Quiz 완료의 url을 /escape/~에서 /quiz/~로 수정함
GetMapping과 PutMapping의 (value = {})를 ()로 수정(다른 controller로와 형식 맞춤)
Resolves: #39

Feat: quiz api url 수정

---

src/main/java/com/project/roomescape/service/RoomService.java

RoomService에서 getAllRooms()에 페이징 관련 주석 추가

Comment:방리스트 조회하기 getAllRooms()에 주석 추가

---

src/main/java/com/project/roomescape/controller/ClueController.java
src/main/java/com/project/roomescape/controller/CommentController.java
src/main/java/com/project/roomescape/controller/GameController.java
src/main/java/com/project/roomescape/controller/QuizController.java
src/main/java/com/project/roomescape/controller/RankController.java
src/main/java/com/project/roomescape/controller/RoomController.java

Rest Api Url을 적합한 규칙에 따라 작성하기 위해서 전체적으로 수정함.
Resolves: #50

Rename:Rest Api Url 규칙에 따른 전체적인 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

question에 ㄱㄴㄷㄹ?를 넣고 content는 null로 변경함
Resolves: #55

Feat: quiz Ca ì수정

---

src/main/java/com/project/roomescape/controller/RoomController.java

url 중복으로 인한 path오류 수정.
방 리스트 조회하기 api url 변경 완료.
Resolves: #50

Fix:Ambiguous handler methods mapped for HTTP path 오류

---

src/main/java/com/project/roomescape/controller/ClueController.java
src/main/java/com/project/roomescape/controller/GameController.java

게임 시작하기 api와 clue 생성하기 api가 같은 시점에 필요
요청을 1번으로 처리하기 위해 게임 시작하기 api에 clue 생성하기 로직도 같이 실행되도록 수정함
Resolves: #66

Feat: 게임 시작하기 api에 clue 생성하기 로직 붙이기

---

.github/workflows/main.yml
.gitignore

buiãpush 나 풀리퀘해야 ìë되는지 알 수 있어서 테스트 중
test

Fix: main.yml 수정

---

src/main/java/com/project/roomescape/controller/ClueController.java
src/main/java/com/project/roomescape/repository/ClueRepository.java
src/main/java/com/project/roomescape/responseDto/ClueResponseDto.java
src/main/java/com/project/roomescape/service/ClueService.java

clue 조회하기 api에서 clueType도 변수로 받아서 해당 contents만 내리는 것으로 수정
Resolves: #72

Feat: clue 조회하기 api 수정

---

.github/workflows/main.yml
.gitignore

Fix: CI test

---

build.gradle
src/main/java/com/project/roomescape/repository/ClueRepository.java
src/main/java/com/project/roomescape/service/ClueService.java
src/test/java/com/project/roomescape/mockobject/MockClueRepository.java
src/test/java/com/project/roomescape/service/QuizServiceTimeTest.java

test 디렉토리에 QuizServiceTimeTest와 MockClueRepository추가. Junit5와 Mockito를 사용하여 테스트 코드 작성.
Clue entity에 존재하지 않는 ClueType 요청 들어올 시에 빈 문자열을 return해주도록 수정.
Resolves: #76, #75

Feat:퀴즈 생성 시간 테스트 코드 추가 && Fix:ClueService NullPointerException 에러 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

Feat: quiz Bb의 ãhint, chance, question 수정

---

.github/workflows/main.yml

build 후 jar 파일이 s3에 잘 저장되는지 test
ㅅResolves: #80

Feat: Actions 스크립트 수정

---

.gitignore
build.gradle
src/main/resources/application.properties
src/main/resources/log4jdbc.log4j2.properties
src/main/resources/logback-spring.xml

로그 설정 파일 logback-spring.xml 추가
DB로그를 남기기 위해 dependencies와 log4jdbc.log4j2.properties추가
application.properties에 db 설정 추가
Resolves: #87

Feat: 로그 설정 파일 추가

---

.github/workflows/main.yml

Feat: actions test

---

.github/workflows/main.yml

github actions test

---

build.gradle
src/main/resources/application.properties
src/main/resources/log4jdbc.log4j2.properties
src/main/resources/logback-access.xml
src/main/resources/logback-spring.xml

기존의 DB로그 설정 삭제하고, 다른 DB로그 설정 적용
HTTP Access log 설정 추가
Ref: #87

Feat: 로그 관련 설정 수정

---

.gitignore
src/main/resources/logback-access.xml
src/main/resources/logback-spring.xml

logback-access.xml 파일 수정
공식문서 참고해서 수정 <encoder> 부분 class 지우니 파일 저장됨
Resolves: #95

Fix: access log가 파일로 저장되지 않는 문제 해결

---

src/main/java/com/project/roomescape/service/QuizService.java

Nginx로 무중단배포 test2

---

scripts/health_check.sh
scripts/run_new_was.sh
scripts/switch.sh

Feat: Nginx로 무중단배포 test3

---

src/main/resources/application.properties

Test: DB 로그 관련 설정 변경

---

scripts/health_check.sh
scripts/run_new_was.sh
scripts/switch.sh
src/main/java/com/project/roomescape/service/QuizService.java

Test: ãNginx test 4

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx test5

---

scripts/health_check.sh
scripts/run_new_was.sh
src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx test 7

---

appspec.yml
scripts/health_check.sh

Test: Nginx test 8

---

appspec.yml
scripts/health_check.sh
scripts/run_new_was.sh
scripts/switch.sh

Test: Nginx 9

---

.github/workflows/main.yml
appspec.yml
scripts/health_check.sh
scripts/run_new_was.sh
scripts/switch.sh

Test: Nginx test 10

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx test 11

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx test 12

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx test 13

---

src/main/java/com/project/roomescape/controller/HealthCheckController.java
src/main/java/com/project/roomescape/service/QuizService.java

Test: health controller 추가

---

scripts/switch.sh
src/main/java/com/project/roomescape/service/QuizService.java

Test: sudo tee 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: last

---

src/main/java/com/project/roomescape/service/QuizService.java

Feat: Nginx 무중단배포 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

Test: Nginx 무중단배포 마ì§test

---

.gitignore
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizCaIntegrationTest.java

Quiz 유형별 quizIntegrationTest 추가했습니다.

Feat:quizIntegrationTest 추가

---

src/test/java/com/project/roomescape/integration/ClueIntegrationTest.java
src/test/java/com/project/roomescape/integration/CommentIntegrationTest.java
src/test/java/com/project/roomescape/integration/GameIntegrationTest.java
src/test/java/com/project/roomescape/integration/RankIntegrationTest.java
src/test/java/com/project/roomescape/integration/RoomIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizCaIntegrationTest.java
src/test/java/com/project/roomescape/mockobject/MockClueRepository.java
src/test/java/com/project/roomescape/service/QuizServiceTimeTest.java

임시로 테스트코드 주석처리
github action에서 테스트코드 build 오류남.

Fix:임시로 테스트코드 주석처리

---

src/main/java/com/project/roomescape/testData/TestDataRunner.java

Fix: aws.properties mysql변경

---

src/main/java/com/project/roomescape/model/GameResource.java

리소스 생성날짜, 수정날짜 확인하기 위해 GameResource extends Timestamped

Feat: GameResource에 createdAt, modifiedAt 추가

---

.gitignore
src/main/java/com/project/roomescape/controller/RankController.java

Fix: nginx 서버 재가동

---

src/main/java/com/project/roomescape/controller/RankController.java

임의로 한개를 켜놓았었는데 푸쉬 후 2개가 가동되야하는데 1개만 되어서 테스트 하는중

Test: Nginx 무중단 테스트 중

---

src/main/java/com/project/roomescape/service/ClueService.java
src/main/java/com/project/roomescape/service/GameService.java
src/main/java/com/project/roomescape/service/RoomService.java

로그에서 주요 기능 식별을 위해 일부 service에 log.info 추가
방 개설하기, 방 참여하기, 게임 시작하기, Clue 생성하기, 게임 종료하기
Resolves: #138

Feat: log 일부 추가

---

src/main/java/com/project/roomescape/service/QuizService.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAaIntegrationTest.java

+ 대신 StringBuilder 사용
12는 상수로 지정

Refactor: createQuizAa 리펙토링

---

src/test/java/com/project/roomescape/integration/ClueIntegrationTest.java
src/test/java/com/project/roomescape/integration/CommentIntegrationTest.java
src/test/java/com/project/roomescape/integration/GameIntegrationTest.java
src/test/java/com/project/roomescape/integration/RankIntegrationTest.java
src/test/java/com/project/roomescape/integration/RoomIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizCaIntegrationTest.java
src/test/java/com/project/roomescape/service/QuizServiceTimeTest.java

테스트 코드 메소드명을 컨벤션에 따라 수정하고 통일시켰습니다.

Refactor:테스트 코드 메소드명 컨벤션에 따른 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

Feat: QuizBa의 chance 수정

---

scripts/switch.sh

스위치 하고 대기하는 포트를 줄이는 기능 추가
Resolves

Feat: Nginx 수정

---

src/main/java/com/project/roomescape/service/QuizService.java

퀴즈 타입 Aa 생성 로직에서 ans값이 0 인 경우도 12를 더하게끔 수정함.

Fix:퀴즈 타입 Aa 생성 로직 수정

---

README.md

브랜치 관리에서 springRTC와 redis 브랜치 내용 추가함.

Docs: README.md 브랜치 관리 추가.

---

src/test/java/com/project/roomescape/integration/RankIntegrationTest.java

Refactor: RankIntegrationTest에서 Order 어노테이션 수정.

---

scripts/run_new_was.sh
src/main/java/com/project/roomescape/service/GameService.java
src/main/resources/logback-spring.xml

logback-spring.xml에서 prod, resource 추가 부분 삭제
run_new_was.sh에서 prod 부분 삭제

Fix: console에 log가 access log만 확인되서 설정 파일 일부 수정함

---

src/main/java/com/project/roomescape/service/RankService.java

Refactor: RankService의 getRanks 리팩토링

---

src/test/java/com/project/roomescape/integration/ClueIntegrationTest.java
src/test/java/com/project/roomescape/integration/CommentIntegrationTest.java
src/test/java/com/project/roomescape/integration/GameIntegrationTest.java
src/test/java/com/project/roomescape/integration/RankIntegrationTest.java
src/test/java/com/project/roomescape/integration/RoomIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizAbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBaIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizBbIntegrationTest.java
src/test/java/com/project/roomescape/integration/quizintegrationtest/QuizCaIntegrationTest.java
src/test/java/com/project/roomescape/service/QuizServiceTimeTest.java

테스트 코드 주석 간소화 및 전체적인 리팩토링을 했습니다.

Refactor:테스트 코드 전체적인 리팩토링
